src/my_twitter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from .views import home_view
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home_view'),
    path('profiles/', include('profiles.urls', namespace="profiles")),
    path('posts/', include('posts.urls', namespace="posts")),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/posts/urls.py
from .views import post_comment_create_and_list_view, like_unlike_post, PostDeleteView, PostUpdateView
from django.urls import path

app_name = 'posts'

urlpatterns = [
	path('', post_comment_create_and_list_view, name='main-post-view'),
	path('liked/', like_unlike_post, name='like-post-view'),
	path('<pk>/delete', PostDeleteView.as_view(), name='post-delete'),
	path('<pk>/update', PostUpdateView.as_view(), name='post-update'),
]

src/profiles/urls.py
from django.urls import path
from .views import (
	my_profile_view, 
	invites_received_view, 
	# invite_profiles_list_view, 
	ProfileListView,
	send_invatation,
	remove_from_friends,
	accept_invatation,
	reject_invatation,
	ProfileDetailView,
	my_friends_view, 
	search_view
)

app_name = 'profiles'

urlpatterns = [
	path('', ProfileListView.as_view(), name="all-profiles-view"),
	path('myprofile/', my_profile_view, name="my-profile-view"),
	path('my-friends/', my_friends_view, name="my_friends_view"),
	path('my-invites/', invites_received_view, name="invites-received-view"),
	# path('to-invite/', invite_profiles_list_view, name="invite-profiles-view"),
	path('send-invite/', send_invatation, name="send-invite"),
	path('remove-friend/', remove_from_friends, name="remove-friend"),
	path('my-invites/accept', accept_invatation, name="accept-invite"),
	path('my-invites/reject', reject_invatation, name="reject-invite"),
	path('<slug>', ProfileDetailView.as_view(), name='profile-detail-view'),
	path('search/', search_view, name="search_view")
]

src/templates/main/home.html
{% extends 'base.html' %}

{% block title %}
Home
{% endblock %}

{% block content %}

	{% if user.is_authenticated %}
	<div class="centered-div">
		<h1>Welcome, {{user}}</h1><br><br>
		<a href="{% url 'posts:main-post-view' %}"><button class="ui button massive primary mb-5">POSTS</button></a><br><br>
		<a href="{% url 'profiles:my-profile-view' %}"><button class="ui button massive primary mb-5">My Profile</button></a><br><br>
		<a href="{% url 'profiles:my_friends_view' %}"><button class="ui button massive primary mb-5">My Friends</button></a>
	</div>
	{% else %}
	<div class="centered-div">
		<h1>Welcome!</h1><br><br>
		<a href="{% url 'account_login' %}"><button class="ui button massive primary mb-5">LogIn</button></a><br><br>
		<a href="{% url 'account_signup' %}"><button class="ui button massive primary mb-5">Register</button></a><br>
	</div>
	{% endif %}

{% endblock %}

{% block scripts %}


{% endblock %}

src/templates/main/navbar.html
{% url 'posts:main-post-view' as path_to_posts %}
{% url 'home_view' as path_to_home %}
{% url 'profiles:my-profile-view' as path_to_my_profile %}
{% url 'profiles:invites-received-view' as path_to_my_invites %}
{# {% url 'profiles:invite-profiles-view' as path_to_invites %} #}
{% url 'profiles:all-profiles-view' as path_to_all_profiles %}
{% url 'profiles:my_friends_view' as path_to_my_friends %}

<div class="ui inverted menu nav mb-7">
  <div class="ui container">
    <a href="{{path_to_home}}" class="{% if request.path == path_to_home %}active{% endif %} item">
        <h3>BekaSTagram</h3>
    </a>
    {% if request.user.is_authenticated %}
    <a href="{{path_to_posts}}" class="{% if request.path == path_to_posts %}active{% endif %} item">
        Board
    </a>
    {% endif %}

    <div class="right menu">
        {% if request.user.is_authenticated %}
        <div class="item">
            <div class="ui floating dropdown icon button teal"> Friends
                <i class="dropdown icon"></i>
                <div class="menu">
                    <a href="{{path_to_my_friends}}" class="{% if request.path == path_to_my_friends %}active{% endif %} item">
                        My Friends
                    </a>
                    <a href="{{path_to_all_profiles}}" class="{% if request.path == path_to_all_profiles %}active{% endif %} item">
                        All Profiles
                    </a>
                
                    <a href="{{path_to_my_invites}}" class="{% if request.path == path_to_my_invites %}active{% endif %} item">
                        Received Invites &nbsp; <div class="ui purple horizontal label">{{invites_num}}</div>
                    </a>
                </div>
             </div>
        </div>
             <div class="item">
              <form action="{% url 'profiles:search_view' %}" method="GET">
                <div class="ui action left icon input">
                <input class="prompt" type="text" name='q' placeholder="name of a friend...">
                <i class="search icon"></i>
                <button type='submit' class="ui button">Search</button>
                </div>
            </form>
            </div>
        
            <a href="{{path_to_my_profile}}" class="{% if request.path == path_to_my_profile %}active{% endif %} item">
                <img src="{{picture.url}}" class="ui avatar image" alt="avatar">&nbsp;
                 {{ request.user }}
            </a>

            <a href="{% url 'account_logout' %}" class="ui item">
                Logout
            </a>
        {% else %}
        <a href="{% url 'account_login' %}" class="ui item">
                Login
            </a>
        {% endif %}
    </div>
  </div>
</div>